---
title: "wrangle / tidy"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dbplyr)
library(RPostgreSQL)
library(lubridate)

require("RPostgreSQL")
drv <- dbDriver("PostgreSQL")
my_db <- dbConnect(drv, dbname = "test_name",
                 host = "ncelections.caocmmq9ap27.us-west-2.rds.amazonaws.com",
                 port = 5432,
                 user = "nc_username", password = "nc_password")
nc_vhis <- tbl(my_db, "nc_vhis")
nc_voter <- tbl(my_db, "nc_voter")
```

```{r nc_wrangle}
nc_vhis <- nc_vhis %>%
  select(county_desc:voting_method, voted_party_desc:ncid) %>%
  mutate(election_lbl = mdy(election_lbl)) %>%
  filter(year(election_lbl) %in% c(2016, 2014, 2012)) %>%
  group_by(election_desc) %>%
  mutate(new_id = paste(voter_reg_num, ncid))# %>%
#  distinct(new_id, .keep_all = TRUE)

nc_voter <- nc_voter %>%
  filter(status_cd == "A") %>%
  select(county_desc:voter_reg_number,
         zip_code,
         race_code:birth_age,
         registr_dt:precinct_desc,
         ncid) %>%
  mutate(new_id = paste(voter_reg_number, ncid))# %>%
#  distinct(new_id, .keep_all = TRUE)

nc <- nc_vhis %>%
  left_join(nc_voter, by = c("new_id")) %>%
  filter(status_cd == "A",
         voting_method != "ELIGIBLE DID NOT VOTE") %>%
  select(county_desc.x,
         voter_reg_num,
         registr_dt,
         zip_code,
         race_code:birth_age,
         precinct_abbrv:precinct_desc,
         election_lbl,
         election_desc) %>%
  rename(county = county_desc.x,
         precinct = precinct_desc,
         party_code = party_cd,
         age = birth_age) #%>%
#  mutate(election_lbl = mdy(election_lbl),
#         registr_dt = mdy(registr_dt))
```

```{r}
elec_day_16 <- as.Date("2016-11-08")
reg_day_16 <- elec_day_16 - 25

# All elligible voters in the registration file
elligible_16 <- nc_voter %>%
  mutate(registr_dt = to_date(registr_dt, "MM/DD/YYYY")) %>% 
  filter(registr_dt <= reg_day_16, status_cd == "A" | status_cd == "S")

# All ballots cast in the November 2016 election
voted_16 <- nc_vhis %>% 
  mutate(election_lbl = to_date(election_lbl, "MM/DD/YYYY")) %>% 
  filter(election_lbl == elec_day_16)

# Join with NA for no vote
nc_16 <- elligible_16 %>% 
  left_join(voted_16, by = c("ncid" = "ncid"))
# save this to the database for quick access?

## How many people voted with each method
#temp <- nc_16 %>% group_by(voting_method) %>% summarise(count = n()) %>% collect()

#sum(temp$count[-which(is.na(temp$voting_method))]) # Number of ballots (4,769,640)
#sum(temp$count) # Number of voters (6,914,248)

## Voter turnout (68.9%)
#sum(temp$count[-which(is.na(temp$voting_method))])/sum(temp$count) 
```

```{r disconnect all}
# rm(list = ls())
```
